### ISSUE TITLE
Deprecation: Addon files in /addon but no preprocessors

### ISSUE THREAD

**Issue by davidbilling** [simplabs/ember-cookies#135]
With version 0.1.0 I get:

DEPRECATION: Addon files were detected in `.../node_modules/ember-simple-auth/node_modules/ember-cookies/addon`, but no JavaScript preprocessors were found for `ember-cookies`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-cookies`'s `package.json`.

**Comment by Turbo87** [comment]
that seems like a very strange issue because v0.1.0 has a dependency on `ember-cli-babel` (see https://github.com/simplabs/ember-cookies/blob/v0.1.0/package.json#L23)

**Comment by davidbilling** [comment]
@Turbo87 Yes indeed. But this is not an issue in 0.1.1
I could not replicate when going back to 0.1.0 since I got alot of other errors.... I will close this
