### ISSUE TITLE
Issues in Interner Explorer

### ISSUE THREAD

**Issue by lobanov-vitaliy** [simplabs/ember-cookies#145]
This line is not working in Interner Explorer
https://github.com/simplabs/ember-cookies/blob/7a7c68d36617ad23978bb6af9481e75f0d3e08a8/addon/services/cookies.js#L9

and babel don't transform this line
https://babeljs.io/docs/plugins/transform-object-assign/#caveats

**Comment by jmmorganMSTS** [comment]
This is also causing issues when running tests under PhantomJS

**Comment by XaserAcheron** [comment]
Boy howdy, does IE11's lack of Object.assign cause some shenanigans. :P

Anyhow, opened a PR (#149) for this, since I happen to be in the neighborhood.
