### ISSUE TITLE
Update ember-getowner-polyfill for babel 6.6.x support

### ISSUE THREAD

**Issue by jrock2004** [simplabs/ember-cookies#170]
The one dependency that you are using `ember-getowner-polyfill` has a newer version where it supports a new version of babel. This is needed as I am see deprecation warning in my ember app

```
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least 
ember-cli-babel 6.6. Version 5.2.8 located: cf2-cli -> ember-cookies -> 
ember-getowner-polyfill -> ember-cli-babel
```

I would make a PR but not sure that is really needed

**Comment by marcoow** [comment]
I think we already allow the latest version of `ember-getowner-polyfill`? see https://github.com/simplabs/ember-cookies/blob/master/package.json#L24

**Comment by BillyRayPreachersSon** [comment]
Out of interest, what version is the minimum version of Ember this addon is trying to support? If it's Ember 2.4, then the `ember-getowner-polyfill` reference can be removed altogether and this warning will go away.

We've managed to get from 29 of these warnings down to 7, and 3 of those are from simplabs addons (`ember-simple-auth` and `ember-cookies`). It would be lovely to have no warnings :)

**Comment by marcoow** [comment]
We're supporting Ember 1.13 and up and thus needs the polyfill unfortunately.

**Comment by BillyRayPreachersSon** [comment]
As with [the comment](https://github.com/simplabs/ember-simple-auth/issues/1577#issuecomment-400774995) against the same issue for ember-simple-auth, would you be able to publish a new major version that doesn't use the polyfill, thus negating the issue of backwards compatibility for those using the new version?
