### ISSUE TITLE
clearAllCookies doesn't seem to work in headless Chrome 68

### ISSUE THREAD

**Issue by zeppelin** [simplabs/ember-cookies#190]
Adding `path=/` seems to fix the issue:

```diff
- document.cookie = `${cookieName}=; expires=${new Date(0).toUTCString()}`;
+ document.cookie = `${cookieName}=; expires=${new Date(0).toUTCString()};path=/`;
```

**Comment by zeppelin** [comment]
Happy to do that! I'm just not an expert in cookies, that's why I only reported the issue and not submitted the PR already :)

**Comment by zeppelin** [comment]
@marcoow could you please review #197?

**Comment by noslouch** [comment]
any chance @marcoow could cut a new release to include #197? This particular issue just bit me as well. For whatever reason, headless chrome (in test contexts only, works ok using it on the CLI), seems to require the path option for clearing.
