### ISSUE TITLE
Cannot read property 'indexOf' of undefined on Fastboot

### ISSUE THREAD

**Issue by josemarluedke** [simplabs/ember-cookies#21]
Hey there!

I was just trying this with the latest ember FastBoot (beta.4) and I get the following error:

```
TypeError: Cannot read property 'indexOf' of undefined at /Users/josemarluedke/Projects/myapp/dist/fastboot/vendor.js:75400:31 at /Users/josemarluedke/Projects/myapp/dist/fastboot/vendor.js:107107:80 at ....
```

The error points to this line: https://github.com/simplabs/ember-cookies/blob/e4b7cec51da57bd00986f658170e99b6d02d7239/addon/services/cookies.js#L129

Note, version used of ember-cookies was 0.0.7.

**Comment by marcoow** [comment]
It looks like the request's `hostname` property has been renamed to `host` in FastBoot - #23 will fix that.
