### ISSUE TITLE
npm deploy build step failed

### ISSUE THREAD

**Issue by SergeAstapov** [simplabs/ember-cookies#335]
According to [CHANGELOG.md](https://github.com/simplabs/ember-cookies/blob/master/CHANGELOG.md) and [releases page](https://github.com/simplabs/ember-cookies/releases) version v0.5.0 has been released.

But https://www.npmjs.com/package/ember-cookies does not have v0.5.0

**Comment by marcoow** [comment]
Looks like the [`deploy` build step](https://github.com/simplabs/ember-cookies/blob/0.5.0/.travis.yml#L44) [doesn't work](https://travis-ci.org/simplabs/ember-cookies/builds/589506916). I published manually for now but this should be fixed.

**Comment by SergeAstapov** [comment]
Thank you @marcoow for fixing this!

I've updated ticket subject to be more generic, feel free to close.
