### ISSUE TITLE
[0.5.1 Regression] TypeError: Cannot read property 'isFastBoot' of undefined

### ISSUE THREAD

**Issue by kpfefferle** [simplabs/ember-cookies#346]
When upgrading from 0.5.0 to 0.5.1 in our app that does not have FastBoot, CI fails with the following error:

```
TypeError: Cannot read property 'isFastBoot' of undefined
```

[Compare view](https://github.com/simplabs/ember-cookies/compare/0.5.0...0.5.1) seems to suggest that quite a bit of logic around FastBoot checking was done in this patch release. It seems to have broken ember-cookies for non-FastBoot apps.

**Comment by marcoow** [comment]
ouch 🤦‍♂ I see what's causing this: https://github.com/simplabs/ember-cookies/compare/0.5.0...0.5.1#diff-2d4817fecea72becc6e3e1b778dfc1d2R58
