### ISSUE TITLE
Add SameSite=None support (and UA check?)

### ISSUE THREAD

**Issue by justinaray** [simplabs/ember-cookies#381]
I was wondering if you'd be willing to add (or accept a PR) for 1st class support for SameSite=None and a UA detect to see if it's supported.

`none` as a value works just fine currently, but it's not documented and there's a wrinkle in using it cross-browser.  Some browsers will ignore the SameSite attribute while others will misinterpret it, effectively using SameSite=Strict.  Because of the later behavior, a feature detect is not possible.

I'm currently supporting this in my projects by either overridding the cookies service write method or checking the UA before adding the sameSite: 'none' attribute to my options list.  I've been using [should-send-same-site-none](https://github.com/linsight/should-send-same-site-none) to check the UA for capatibility.

Technically, None is only in draft spec, so I would understand your resistance.  But, with Chrome shipping it next week and both FF and Edge signaling intent to ship, it might make sense.

Let me know if you'd need more info or would consider adding it.  I can share more of what I've done.

**Comment by marcoow** [comment]
As you say this is already supported since we don't actually check that the value you're passing is one of the documented ones ;) I'll update that in the documentation. I think checking whether the UA actually support a value that you set is out os scope for ember-cookies.

**Comment by catz** [comment]
Hello Marco,

It's not directly related to this ticket and not sure whether it's helpful or not, but in our project I added typings for ember-cookies like this. If you find this useful you may add it into index.d.ts in the root folder.

```
declare module 'ember-cookies/services/cookies' {
  import Service from '@ember/service';

  type ReadOptions = {
    raw?: boolean;
    domain?: never;
    expires?: never;
    maxAge?: never;
    path?: never;
  };

  type WriteOptions = {
    domain?: string;
    path?: string;
    secure?: boolean;
    raw?: boolean;
    sameSite?: 'Strict' | 'Lax' | 'None';
    signed?: never;
  } & (
    | { expires?: Date; maxAge?: never }
    | { maxAge?: number; expires?: never }
  );

  type ClearOptions = {
    domain?: string;
    path?: string;
    secure?: boolean;

    expires?: never;
    maxAge?: never;
    raw?: never;
  };

  export default class CookiesService extends Service {
    public read(name: string, options?: ReadOptions): string;
    public write(name: string, value: unknown, options?: WriteOptions): void;
    public clear(name: string, options?: ClearOptions): void;
    public exists(name: string): boolean;
  }
}
```

**Comment by marcoow** [comment]
@catz I think that would be cool, yes.
