### ISSUE TITLE
Can't be used without FastBoot

### ISSUE THREAD

**Issue by jsmecham** [simplabs/ember-cookies#4]
It's currently not possible to use this addon without also including the FastBoot addon. Any attempt to inject the service results in `Attempting to inject an unknown injection: service:fastboot` errors.

**Comment by marcoow** [comment]
Yeah, it will definitely be possible to use this without having `ember-cli-fastboot` installed as well eventually.

Just not done yet…

**Comment by jsmecham** [comment]
No worries. Just jumping the gun a little bit in preparation... :)

**Comment by marcoow** [comment]
This is fixed in 0.0.2
