### ISSUE TITLE
Null reference for some cookies 

### ISSUE THREAD

**Issue by jmimi** [simplabs/ember-cookies#51]
For some cookies there is null pointer exception in [line](https://github.com/simplabs/ember-cookies/blob/master/addon/services/cookies.js#L38).
And for this exception my `sessionAuthenticated` hook in ESA failed.
The cookie cause : `" swagger-editor-development-mode:true"` with no name

**Comment by marcoow** [comment]
Are you on the latest version of ember-cookies? Actually #34 should fix this.

**Comment by jmimi** [comment]
I'm using ESA version 1.2.0 actually.

**Comment by marcoow** [comment]
This will be fixed in ESA by simplabs/ember-cookies#51
