### ISSUE TITLE
ember-getowner-polyfill is deprecated

### ISSUE THREAD

**Issue by tsteuwer** [simplabs/ember-cookies#62]
```DEPRECATION: ember-getowner-polyfill is now a true polyfill. Use Ember.getOwner directly instead of importing from ember-getowner-polyfill [deprecation id: ember-getowner-polyfill.import]```

**Comment by marcoow** [comment]
ember-cookies [does not import from `ember-getowner-polyfill`](https://github.com/simplabs/ember-cookies/search?utf8=✓&q=ember-getowner-polyfill&type=Code). Instead if uses the polyfilled `getOwner` API.

**Comment by tsteuwer** [comment]
Then shouldn't it be removed from the dependencies?

https://github.com/simplabs/ember-cookies/blob/master/package.json#L24

**Comment by marcoow** [comment]
No, this is still a polyfill that we need to support older Ember versions.
