### ISSUE TITLE
ember-getowner-polyfill is deprecated

### ISSUE THREAD

**Issue by Godfather27** [simplabs/ember-cookies#91]
DEPRECATION: ember-getowner-polyfill is now a true polyfill. Use Ember.getOwner directly instead of importing from ember-getowner-polyfill

the package is still in the dependencies

**Comment by marcoow** [comment]
This is not coming from ember-cookies, see https://github.com/simplabs/ember-cookies/search?utf8=✓&q=getowner&type=
